#---------------------------------------------------
#General Parameters 
#---------------------------------------------------
SAMPLES: "samples.tsv"
reSAMPLES: "reSamples.tsv" #Renamed samples 
CONTROL: "control.tsv"
TREAT: "treat.tsv" 
FINAL: "groups.tsv"
MEMORY: "-Xmx20g" #for 20giga, change as much giga as you have 
CORES: 8
#------------------------------------------------------------------
#Change this set of parameters if you wish to run at Genome level 
#------------------------------------------------------------------
GENOME: "/nfs/turbo/umms-thahoang/sherine/REFERENCES/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa"
GTF: "/nfs/turbo/umms-thahoang/sherine/REFERENCES/Homo_sapiens/UCSC/hg38/Annotation/Genes/genes.gtf" 
INDEX: "/nfs/turbo/umms-thahoang/sherine/REFERENCES/Homo_sapiens/UCSC/hg38/Sequence/Bowtie2Index/genome" 
Num_Processors: 4
BINSIZE: 1
Genome_Size: 2913022398  # GRCm38 2652783500 
